# Generated by Django 4.1.7 on 2023-02-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_vote_remove_candidate_votes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddField(
            model_name='candidate',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
