# Generated by Django 4.1.7 on 2023-02-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_delete_vote_candidate_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='address',
            field=models.CharField(default='not provided', max_length=500),
        ),
    ]
