# Generated by Django 4.1.7 on 2023-02-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_candidate_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='age',
        ),
    ]
