# Generated by Django 4.1.7 on 2023-03-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_remove_candidate_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
