# Generated by Django 4.1.7 on 2023-03-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_candidate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='user',
            field=models.CharField(max_length=100, verbose_name='Candidate'),
        ),
    ]
