# Generated by Django 4.1.7 on 2023-03-01 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_candidate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='image',
        ),
    ]
